name: Release Please

on:
  push:
    branches: [main]

# release-please-action needs write access to open release PRs and push tags.
permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    uses: 1121citrus/shared-github-workflows/.github/workflows/release-please.yml@7736674092013c10af60f105cc8b6bccb7571afa
    secrets: inherit
